### ISSUE TITLE
Addon actions, the logs have no details

### ISSUE THREAD

**Issue by gcusnieux** [gravitee-io/gravitee-ui-components#243]
Since the storybook 6.x update, the action addon logs no longer contain the details of the event.

![Capture d’écran 2021-01-15 à 15 53 37](https://user-images.githubusercontent.com/1457497/104741722-dd2ee800-5749-11eb-9e5d-c38cd918072d.png)

**Comment by gaetanmaisse** [comment]
The issue is somehow related to [`i18nKnob`](https://github.com/gravitee-io/gravitee-ui-components/blob/master/stories/lib/i18n-knob.js) as disabling it fixes the pb but I don't know why yet 🤔 

Maybe moving i18 management to the toolbar (see https://github.com/gravitee-io/gravitee-ui-components/issues/238) will fix this too 🤷🏻 .

**Comment by gaetanmaisse** [comment]
I will work to fix that on Storybook side, for followup see: https://github.com/storybookjs/storybook/issues/8544
